const Languages = ["Afrikaans",
"Albanian",
"Amharic",
"Arabic",
"Arabic (Egypt)",
"Armenian",
"Azerbaijani",
"Bajan",
"Basque (Euskara)",
"Belarusian",
"Bemba",
"Bengali",
"Bislama",
"Bosnian",
"Breton",
"Bulgarian",
"Burmese",
"Catalan",
"Cebuano",
"Chamorro",
"Chinese (Simplified)",
"Chinese (Traditional - Hong Kong)",
"Chinese (Traditional - Macau)",
"Chinese (Traditional - Taiwan)",
"Classical Greek",
"Comorian, Ngazidja",
"Creole English (Antigua and Barbuda)",
"Creole English (Bahamas)",
"Creole English (Grenada)",
"Creole English (Guyana)",
"Creole English (Haiti)",
"Creole English (Jamaican)",
"Creole English (Saint Vincent and the Grenadines)",
"Creole English (Virgin Islands)",
"Creole French (Saint Lucia)",
"Creole French (Seychelles)",
"Croatian",
"Czech",
"Danish",
"Dari",
"Dutch (Belgium)",
"Dutch (Netherlands)",
"Dzongkha",
"English (GB)",
"English (USA)",
"Esperanto",
"Estonian",
"Faroese",
"Farsi",
"Filipino/Tagalog",
"Finnish",
"French (Belgium)",
"French (Canada)",
"French (France)",
"French (Switzerland)",
"Galician",
"Ganda",
"Georgian",
"German",
"German (Switzerland)",
"Greek",
"Gujarati",
"Hausa",
"Hawaiian",
"Hebrew",
"Hindi",
"Hungarian",
"Icelandic",
"Indonesian",
"Inuktitut, Greenlandic",
"Irish Gaelic",
"Italian",
"Italian (Switzerland)",
"Japanese",
"Javanese",
"Kabuverdianu",
"Kannada",
"Kazakh",
"Khmer",
"Kinyarwanda",
"Kirundi",
"Korean",
"Kurdish Kurmanji (Latin script)",
"Kurdish Sorani (Arabic script)",
"Kyrgyz",
"Lao",
"Latin",
"Latvian",
"Lingala",
"Lithuanian",
"Luxembourgish",
"Macedonian",
"Malagasy",
"Malay",
"Malayalam",
"Maldivian",
"Maltese",
"Maori",
"Marathi",
"Mongolian",
"Montenegrin",
"Morisyen",
"Moroccan Arabic",
"Nepali",
"Norwegian",
"Nyanja",
"Palauan",
"Papiamentu",
"Pashto",
"Polish",
"Portuguese (Brazil)",
"Portuguese (Portugal)",
"Punjabi",
"Quechua",
"Romanian",
"Russian",
"Samoan",
"Scots Gaelic",
"Serbian",
"Shona",
"Sinhala",
"Slovak",
"Slovenian",
"Somali",
"Sotho, Southern",
"Spanish (Latin America)",
"Spanish (Spain)",
"Spanish (US)",
"Swahili",
"Swedish",
"Tajik",
"Tamil (India)",
"Tamil (Sri Lanka)",
"Telugu",
"Thai",
"Tibetan",
"Tigrinya",
"Tok Pisin",
"Tongan",
"Tswana",
"Turkish",
"Turkmen",
"Ukrainian",
"Urdu",
"Uzbek",
"Vietnamese",
"Welsh",
"Xhosa",
"Yoruba",
"Zulu",];

export default Languages;